print ('Herbert Wang\n''8101 Leslie St.\n''Thornhill, ON L3T 7P4\n\n')
print ('          Mr. Joesph Servidio')
print ('          8101 Leslie St.')
print ('          Suite Office')
print ('          Thornhill, ON L3T 7P4')